name: Nixpkgs update
on:
  schedule:
    # Every hour
    - cron: '0 * * * *'

  # Allow triggering manually from the Actions Tab
  workflow_dispatch:

jobs:
  update:
    name: Update all nixpkgs sources
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.2
      with:
        # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        persist-credentials: false
    - uses: cachix/install-nix-action@v10
      with:
        skip_adding_nixpkgs_channel: true
    - name: Building updater
      run: nix-build -A nixpkgsUpdater
    - name: Running updater
      run: ./result
    - name: Commit updates
      # FIXME: This doesn't appear to work if the git status is removed
      # The `if` check just seems to be ignored then
      # and the commit block is always ran
      run: |
        git status
        if ! git diff-files --quiet; then
          echo "Changes detected, committing them"
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Automatic niv update" -a
        else
          echo "No changes detected"
        fi
    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        # Apparently we need to use a separate GITHUB_TOKEN (not the
        # autogenerated one available during each workflow) if we want the push
        # to trigger another workflow (we need to trigger the push.yml workflow
        # to run tests and update the DockerHub images)
        github_token: ${{ secrets.UPDATE_GITHUB_TOKEN }}
