name: Tests
on:
  pull_request:
    branches:
      - master

jobs:
  testing:
    name: Run image tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v10
      with:
        skip_adding_nixpkgs_channel: true
    - name: Run tests
      run: tests/run-tests
