name: Test & image update
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  testing:
    name: Run image tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v10
      with:
        skip_adding_nixpkgs_channel: true
    - name: Build test runner
      run: nix-build -A testRunner
    - name: Run tests
      run: ./result
  image-update:
    name: Build and push image update
    runs-on: ubuntu-latest
    needs: testing
    # Only push image updates to DockerHub for master commits
    if: github.event_name == 'push'
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v10
      with:
        skip_adding_nixpkgs_channel: true
    - name: Build updater
      run: nix-build -A imageUpdater
    - name: Running updater
      env:
        REGISTRY_USER: niteo
        REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      run: ./result
